# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BacSiViet.VN' do
    pod 'AFNetworking', '~> 3.0'
    
    pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :tag => '0.5.1'
    pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :tag => '0.5.5'
    pod 'SearchEmojiOnString'
    pod 'UIAlertView+Blocks'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'MPGNotification'
end

